name: Run iCal Script

on:
  schedule:
    - cron: "0 */4 * * *" # Runs every 4 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests ics pytz

      - name: Run iCal script
        run: python iCal_3to1.py

      - name: Upload generated .ics file (L5)
        uses: actions/upload-artifact@v4
        with:
          name: iCal-Output-L5
          path: Booked_L5.ics

      - name: Upload generated .ics file (PH)
        uses: actions/upload-artifact@v4
        with:
          name: iCal-Output-PH
          path: Booked_PH.ics

      - name: Upload generated .ics file (Public_PH.ics)
        uses: actions/upload-artifact@v4
        with:
          name: iCal-public_Output-PH
          path: Public_PH.ics

      - name: Upload generated .ics file (Public_L5.ics)
        uses: actions/upload-artifact@v4
        with:
          name: iCal-Public_Output-L5
          path: Public_L5.ics

      - name: Commit and push generated .ics files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Booked_L5.ics Booked_PH.ics Public_PH.ics Public_L5.ics
          git commit -m "Update generated iCal files" || echo "No changes to commit"
          git push
