name: Run iCal Script

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:        # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install requests ics pytz

      - name: Run iCal script
        run: python iCal_3to1.py

      - name: Upload generated .ics file (L5)
        uses: actions/upload-artifact@v4
        with:
          name: iCal-Output-L5
          path: Booked_L5.ics

      - name: Upload generated .ics file (PH)
        uses: actions/upload-artifact@v4
        with:
          name: iCal-Output-PH
          path: Booked_PH.ics

      - name: Upload generated .ics file (Public_PH.ics)
        uses: actions/upload-artifact@v4
        with:
          name: iCal-public_Output-PH
          path: Public_PH.ics

      - name: Upload generated .ics file (Public_L5.ics)
        uses: actions/upload-artifact@v4
        with:
          name: iCal-Public_Output-L5
          path: Public_L5.ics

      - name: Commit and Push Generated .ics
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add Booked_L5.ics
          git commit -m 'Booked_L5.ics' || echo "No changes to commit"
          git push
          git add Booked_PH.ics
          git commit -m 'Booked_PH.ics' || echo "No changes to commit"
          git push
          git add Public_PH.ics
          git commit -m 'Public_PH.ics' || echo "No changes to commit"
          git push
          git add Public_L5.ics
          git commit -m 'Public_L5.ics' || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
