name: Run iCal Script

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:        # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install requests ics pytz

      - name: Run iCal script
        run: python iCal_3to1.py

      - name: Upload generated .ics file
        uses: actions/upload-artifact@v4
        with:
          name: iCal-Output
          path: DownTownSkagen_SourceAndTime.ics

      - name: Commit and Push Generated .ics
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add calendar.ics
          git commit -m 'Update DownTownSkagen_SourceAndTime.ics'
          git push
